- name: Naikkan aplikasi web server dari ECR
  hosts: node1
  become: true
  vars:
    docker_users: [ubuntu]
    ecr_registry: "721046591371.dkr.ecr.ap-southeast-1.amazonaws.com"
    ecr_image: "{{ ecr_registry }}/devops-bootcamp/final-project-faris:v1"
    aws_region: "ap-southeast-1"

  roles:
    - geerlingguy.docker

  tasks:
    - name: Pasang kebergantungan (unzip, curl, python3-docker)
      apt:
        name:
          - unzip
          - curl
          - python3-docker
        state: present
        update_cache: true

    - name: Pasang AWS CLI v2 jika belum ada
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
        unzip -o /tmp/awscliv2.zip -d /tmp
        /tmp/aws/install --update
        rm -rf /tmp/aws /tmp/awscliv2.zip
      args:
        creates: /usr/local/bin/aws

    - name: Login ke ECR guna IAM role instance
      shell: >
        /usr/local/bin/aws ecr get-login-password --region {{ aws_region }} |
        docker login --username AWS --password-stdin {{ ecr_registry }}
      changed_when: false

    - name: Tarik imej terkini dari ECR
      community.docker.docker_image:
        name: "{{ ecr_image }}"
        source: pull

    - name: Hentikan & keluarkan container lama (jika ada)
      community.docker.docker_container:
        name: ship-app
        state: absent

    - name: Naikkan container baharu
      community.docker.docker_container:
        name: ship-app
        image: "{{ ecr_image }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "80:80"
